# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: test.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ntest.proto\x12\x04test\x1a\x1bgoogle/protobuf/empty.proto\"\x19\n\tTimeReply\x12\x0c\n\x04time\x18\x01 \x01(\x03\x32z\n\x04\x43mod\x12<\n\x08NullFunc\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\"\x00\x12\x34\n\x07GetTime\x12\x16.google.protobuf.Empty\x1a\x0f.test.TimeReply\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'test_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _TIMEREPLY._serialized_start=49
  _TIMEREPLY._serialized_end=74
  _CMOD._serialized_start=76
  _CMOD._serialized_end=198
# @@protoc_insertion_point(module_scope)
